namespace Lertaro.PluginSdk.Abstractions.Plugins;

/// <summary>
/// Represents a provider that generates dynamic action items at runtime
/// (e.g. the dynamic Windows Shell Context Menu).
/// </summary>
public interface IDynamicActionProvider : IPluginComponent
{
    /// <summary>The group name this dynamic action provider belongs to (e.g., "Shortcut Menu").</summary>
    string GroupName { get; }

    /// <summary>The display name of the provider.</summary>
    string IPluginComponent.Name => GroupName;

    /// <summary>Display order in the action menu. Lower values appear first. Default: 0.</summary>
    int Priority => 0;

    /// <summary>
    /// The words this provider is reachable by. Their only effect today is the one <see cref="IsVisibleInMenu"/>
    /// shows: a provider that declares keywords opts OUT of the root actions menu, because it is meant to be
    /// reached by typing rather than by clicking. The host does NOT match these words against the search box
    /// (unlike <see cref="ISearchResultAction.Keywords"/>, which dispatches on them, and
    /// <see cref="IInstantResultProvider.QueryTriggerKeywords"/>, which the host strips off the file search),
    /// and they are not in its trigger-word inventory either -- so a provider that declares keywords and
    /// expects them to answer in the search box will sit unreachable there.
    /// </summary>
    IReadOnlyList<string> Keywords => Array.Empty<string>();

    /// <summary>Parameter names used for displaying the search-result form of this provider.</summary>
    IReadOnlyList<string> Parameters => Array.Empty<string>();

    /// <summary>Determines whether this provider is visible in the search result matching for the given window type.</summary>
    bool IsVisibleInSearch(IReadOnlyList<ISearchResult> results, SearchWindowType windowType) => true;

    /// <summary>Determines whether this provider should be visible in the right-click / action menu.</summary>
    bool IsVisibleInMenu(IReadOnlyList<ISearchResult> results, SearchWindowType windowType) => Keywords.Count == 0;

    /// <summary>
    /// Called by the host at most once per process, the first time any actions menu starts opening --
    /// before CanProvide/GetMenuItems are actually invoked. The host guarantees this, so implementations
    /// don't need to guard against repeat calls themselves. Lets a provider kick off slow one-time setup
    /// (e.g. warming up a native worker thread) with a genuine head start instead of racing its own
    /// CanProvide/GetMenuItems call, which happen back-to-back with no lead time of their own. Must not
    /// block; do any real work on a background thread. Default: no-op.
    /// </summary>
    void Init() { }

    /// <summary>Determines if this provider can handle the given (one or more) search results.</summary>
    bool CanProvide(IReadOnlyList<ISearchResult> results);

    /// <summary>
    /// Whether this provider has actions for INSTANT results -- the rows an instant-result provider
    /// contributes (the window switcher's windows, a calculator's answer, ...). Default: false.
    /// </summary>
    /// <remarks>
    /// The host keeps the actions menu closed for instant results by default: they carry no file path, so
    /// the built-in shell actions have nothing to act on and would render as a list of dead rows. A
    /// provider that genuinely acts on such a result has to say so here, and the host then opens the menu
    /// for it -- this flag is a cheap declaration, not a promise: the host still asks
    /// <see cref="CanProvide"/> before showing anything, so an instant result this provider cannot handle
    /// keeps the menu closed rather than opening it empty.
    /// </remarks>
    bool CanProvideForInstantResults => false;

    /// <summary>
    /// Populates and returns menu items for the root menu (hMenu = Zero) or a sub-menu.
    /// </summary>
    IEnumerable<DynamicMenuItem> GetMenuItems(IReadOnlyList<ISearchResult> results, IntPtr hMenu);

    /// <summary>
    /// Returns lightweight hotkey→execute pairs for use in HotkeyActionTrigger.
    /// Default: empty (provider does not expose hotkeys).
    /// Override for O(1) hotkey lookup without a full GetMenuItems call.
    /// </summary>
    IEnumerable<(string Hotkey, Action Execute)> GetHotkeyActions(IReadOnlyList<ISearchResult> results)
        => Array.Empty<(string, Action)>();

    /// <summary>Invokes a dynamic command by its ID against the given (one or more) search results.</summary>
    void ExecuteCommand(IReadOnlyList<ISearchResult> results, uint commandId, IntPtr ownerHwnd);

    /// <summary>Cleans up any allocated session resources (e.g., when exiting the action list).</summary>
    void ClearSession();
}

/// <summary>
/// Represents an individual menu item generated by a dynamic provider.
/// </summary>
public class DynamicMenuItem
{
    /// <summary>
    /// Optional Quick Navigation root update, started after the popup opens. Empty Text reserves an
    /// invisible insertion point; null removes the item, and returning this item keeps it unchanged.
    /// Honor cancellation before allocating session handles. The host invokes this on its UI thread.
    /// </summary>
    public Func<CancellationToken, Task<DynamicMenuItem?>>? LoadDeferredItem { get; set; }
    /// <summary>Place this Quick Navigation root item above provider groups, with a separator below it.</summary>
    public bool IsPinnedToTop { get; set; }
    public string Text { get; set; } = string.Empty;
    public uint CommandId { get; set; }
    public bool IsSeparator { get; set; }
    public bool HasSubMenu { get; set; }
    public IntPtr SubMenuHandle { get; set; }
    public bool IsDisabled { get; set; }
    /// <summary>Navigation eligibility from provider metadata; null asks the host to check. True is revalidated on execution.</summary>
    public bool? IsPathAvailable { get; set; }
    /// <summary>
    /// Whether clicking/Enter on this item executes anything. Default: true. Set false for a pure
    /// category/group node (no real target of its own) so it can only be drilled into via its submenu
    /// (hover/keyboard-focus/right-arrow) -- a click on it does nothing instead of closing the host menu.
    /// </summary>
    public bool IsActionable { get; set; } = true;
    public IntPtr HBitmapItem { get; set; }
    /// <summary>
    /// Optional direct invocation delegate set by the plugin.
    /// When non-null, the host calls this instead of routing through
    /// <see cref="IQuickNavigationProvider.ExecuteCommand"/> or path navigation.
    /// Plugins use this for items whose execution logic they own entirely
    /// (e.g. virtual Shell namespace items, custom actions).
    /// </summary>
    public Action? OnExecute { get; set; }
    /// <summary>
    /// A single letter that activates this item while the menu is open, shown next to the item as well
    /// as being a trigger (case-insensitive). Default: empty, meaning the item has no mnemonic.
    /// </summary>
    /// <remarks>
    /// The host matches a typed letter against this only while the menu's own filter box is empty, so
    /// letters never steal the first keystroke of a filter. A longer value (e.g. "Ctrl+O") is display
    /// only and is never matched -- it is a hotkey, not a mnemonic.
    /// </remarks>
    public string ShortcutHint { get; set; } = string.Empty;
    /// <summary>
    /// Marks this as a non-rendered continuation cursor for a paged submenu. The quick-navigation
    /// host fetches <see cref="SubMenuHandle"/> automatically as the user scrolls near the end of the
    /// current page, rather than showing this item as a "load more" row.
    /// </summary>
    public bool IsContinuation { get; set; }
    /// <summary>
    /// Renders as a non-clickable section header (like a Quick Navigation submenu's own group name)
    /// instead of a normal row. Text is the header label; if OnExecute is also set, a small button
    /// appears at the header's trailing edge invoking it (e.g. "add an entry to this category") --
    /// clicking anywhere else on the header does nothing. HasSubMenu/CommandId/IsSeparator/IsDisabled/
    /// HBitmapItem/IsActionable are ignored when this is true.
    /// </summary>
    public bool IsHeader { get; set; }
}
